### ISSUE TITLE
Show explanatory error messages when calling multisite_account.json was unsuccessful

### ISSUE THREAD

**Issue by tanius** [gdpelican/edgeryders-form#1]
There are a few possible error messages. For each, below is what the application shows right now, what the error message says, and a proposal what the application should display.

Our preferred solution would be a kind of translation table in the software, configured via a JSON or YAML file, where Discourse errors like `"email": ["has already been taken"]` are mapped to user-friendly error messages specific for an installation of this software.

## When the primary e-mail has been taken

For that case, the application so far shows, on the last page and in red:

> TypeError: Cannot read property '0' of undefined

We'd like a friendly message that the user can understand, such as:

> It seems you already have an account on our forum using this e-mail address. Please choose a different e-mail address and click again on "Send".

The error can be detected from `success: false` in the API response, and the associated "errors" object:

```
{
  "success": false,
  "message": "Primary email has already been taken",
  "errors": {
    "email": [
      "has already been taken"
    ]
  },
  "values": {
    "name": "user_81",
    "username": "user_81",
    "email": "mail@example.com"
  },
  "is_developer": false
}
```

## When the username is not unique

For that case, the application so far shows, on the last page and in red:

> TypeError: Failed to fetch

We'd like a friendly message that the user can understand, such as:

> It seems somebody has already chosen your preferred username / nickname. Please enter a different one and click again on "Send".

The API response by Discourse is in this case:

```
{
  "success": false,
  "message": "Username must be unique",
  "errors": {
    "username": [
      "must be unique"
    ]
  },
  "values": {
    "name": "user_43",
    "username": "user_43",
    "email": "mail@example.com"
  },
  "is_developer": false
}
```

## Combined cases

It is also possible to get multiple of the above errors at once. For example:

```
{
  "success": false,
  "message": "Username must be unique\nPrimary email has already been taken",
  "errors": {
    "username": [
      "must be unique"
    ],
    "email": [
      "has already been taken"
    ]
  },
  "values": {
    "name": "test03_43",
    "username": "test03_43",
    "email": "test03@edgeryders.eu"
  },
  "is_developer": false
}
```

**Comment by tanius** [comment]
Even better, there could be an internal translation table of Discourse error messages to user-friendly error messages for this application. So when encountering "Primary email has already been taken", the application would show something like "It seems you already have an account on our forum using this e-mail address. Please choose a different e-mail address and click again on 'Send'."

**Comment by tanius** [comment]
I tested this again with the latest available version (3769efb). Namely I tested the case of "e-mail has already been taken". Result:

The server answered with "200 OK" and the following error message (with values redacted by me):

```
{
    "success":false,
    "message":"Primary email has already been taken",
    "errors":{
        "email":["has already been taken"]
    },
    "values":{
        "name":"…",
        "username":"…",
        "email":"…"
    },
    "is_developer":false
}
```

However the Vue.js client software did not do anything noticable. It did not display an error message, and still displayed the screen to enter name, age and e-mail address.

(That you get "200 OK" back together with an error message is a bug in the API. Please work around that for now, [we'll fix it later](https://github.com/edgeryders/discourse/issues/224).)

**Comment by gdpelican** [comment]
Oof whyyy does it respond with code 200?

**Comment by tanius** [comment]
> Oof whyyy does it respond with code 200?

I know! Never noticed this before somehow, and totally confused myself when testing. There's no reason other than that it's by mistake …

**Comment by gdpelican** [comment]
Do you think it's better to adapt the vue code to that, or put in a patch
to the milti site plugin? (Assuming equal difficulty) are there other
consumers of that endpoint that might break with a status change there?

**Comment by tanius** [comment]
Your Vue.js application is so far the only API client of `multisite_account.json`. So yes, if you want to go for the clean solution (which I'd welcome), you can send us a patch for the multisite account creation plugin. It's about [this line](https://github.com/edgeryders/discourse/blob/multisite/plugins/edgeryders-multisite-accounts/plugin.rb#L50) it seems.

Since this is not part of your original task, let's give it extra budget. Just add to the invoice based on the time this will take, but let me know in the unlikely case when it starts to go beyond 3 hours. (You may have to send a separate invoice for this, but that's another issue … .)

**Comment by gdpelican** [comment]
The change wants to be to add a status to that line, so it reads
```
return render json: response, status: :unprocessable_entity unless response['success']
```
; I reckon that'll do us.

I've spent a bit of time on very patchy internet trying to get a PR together, but it's been a rough time so far. Would you be up for putting that change in? I reckon that will get our error messages to start going properly.

**Comment by gdpelican** [comment]
I've put up a proper PR for this now here:
https://github.com/edgeryders/discourse/pull/226

**Comment by gdpelican** [comment]
@tanius any word on this one?

**Comment by tanius** [comment]
With your edgeryders/discourse#226 pull request (for now installed as a patch only), it seems to work all fine now :-) As in, I get a proper error message when trying to post with an e-mail address that already has an account associated to it in Discourse. Thank you!
