### ISSUE TITLE
Don't include the e-mail address in posts

### ISSUE THREAD

**Issue by tanius** [gdpelican/edgeryders-form#2]
It seems to me (from the POST request sent, even though I did not yet manage to make that successful) that the Discourse topic created by this application on the platform will include the user's e-mail address in the title, like this:

> Rethinking retirement - response by mail@example.com

And also at the bottom of the post itself, like this:

> **name:** example_username
> **age:** 34
> **email:** mail@example.com

Please use the username / nickname / handle instead of the e-mail address in the title, and omit the e-mail address from the bottom of the post. This is for privacy reasons … this is Europe, and they have complicated things over here :smile: 

Discourse staff users can still see the e-mail address by looking at the user account record in the Discourse admin section.

**Comment by gdpelican** [comment]
Cool, I've made this change
