### ISSUE TITLE
Create the username based on "name/nickname", not based on "e-mail address"

### ISSUE THREAD

**Issue by tanius** [gdpelican/edgeryders-form#3]
I'm not sure what we said originally about this, but I now think that creating the Discourse username based on the first part of the e-mail address (as done now) is a minor privacy issue. Because most people have Gmail addresses, and taken together with a look into the source code it would be possible to guess their e-mail addresses.

Also, people don't expect their e-mail address to be published, in full or in part and would be at least surprised. Not so when creating the Discourse username based on what they enter into the "Name/nickname" field. Combining that with a number (e.g. `maria_12`) like now can be kept up.

**Comment by gdpelican** [comment]
Fixed!
