### ISSUE TITLE
Provide a tooltip for the top-right "Cancel" button

### ISSUE THREAD

**Issue by tanius** [gdpelican/edgeryders-form#5]
All other buttons have tooltips, just not the top-right "X" button to cancel the questionnaire. Would be good to have a tooltip there as well, esp. since that button is the only one that will lead to loss of data if pressed accidentally. So the tooltip should probably express that, for example:

> Clear all answers and start again.

**Comment by gdpelican** [comment]
Cool, this one should be resolved
